# Generated by Django 6.0.4 on 2026-04-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSiteMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='サイト名')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'オファーサイト',
                'db_table': 'offer_site_masters',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企業名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('source_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offersitemaster', verbose_name='取得元サイト')),
            ],
            options={
                'verbose_name': '企業',
                'db_table': 'companies',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='企業概要')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='平均年収（万円）')),
                ('overtime', models.IntegerField(blank=True, null=True, verbose_name='平均残業時間（時間/月）')),
                ('black_score', models.IntegerField(blank=True, null=True, verbose_name='ブラック度（1〜5）')),
                ('raw_response', models.TextField(blank=True, verbose_name='AIの生レスポンス')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析日時')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '企業分析',
                'db_table': 'company_analyses',
            },
        ),
    ]
